[providers]
providers = ['node']

[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['sh -c "if [ -d backend ]; then cd backend; fi && npm install"']

[phases.build]
cmds = ['sh -c "if [ -d backend ]; then cd backend; fi && npx prisma generate"']

[start]
cmd = 'sh -c "if [ -d backend ]; then cd backend; fi && node src/server.js"'
