/**
 * Application Constants for School Management System Backend
 */

export const SYSTEM_ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
  STAFF: 'STAFF',
  TENANT_USER: 'TENANT_USER'
});

export const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
});

export const ERROR_CODES = Object.freeze({
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RELATIONSHIP_CONFLICT: 'RELATIONSHIP_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TENANT_ACCESS_ERROR: 'TENANT_ACCESS_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  // Authentication Specific Error Codes
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_FIREBASE_TOKEN: 'INVALID_FIREBASE_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  IDENTITY_CONFLICT: 'IDENTITY_CONFLICT'
});


export const TOKEN_TYPES = Object.freeze({
  RESET: 'RESET',
  SETUP: 'SETUP'
});

export const AUTH_CONSTANTS = Object.freeze({
  ACCESS_TOKEN_ALGORITHM: 'HS256',
  ACCESS_TOKEN_EXPIRY: '7d',
  ACCESS_TOKEN_EXPIRY_SECONDS: 604800,
  REFRESH_TOKEN_EXPIRY_DAYS: 30,
  REFRESH_TOKEN_BYTES: 32,
  REFRESH_TOKEN_HEX_LENGTH: 64,
  REFRESH_COOKIE_NAME: 'sms_refresh_token',
  REFRESH_COOKIE_PATH: '/api/v1/auth',
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  PASSWORD_RESET_TOKEN_EXPIRY_MINUTES: 15,
  PASSWORD_SETUP_TOKEN_EXPIRY_HOURS: 24,
  RESET_TOKEN_BYTES: 32,
  LOCKED_PASSWORD_PREFIX: '!LOCKED_',
  FIREBASE_LOCKED_PASSWORD_PREFIX: '!LOCKED_FIREBASE_AUTH_MANAGED',
  FUTURE_AUTH_LOCKED_PREFIX: '!LOCKED_FUTURE_AUTH_REQUIRED',
  PARENT_NO_DIRECT_AUTH_PREFIX: '!LOCKED_PARENT_NO_DIRECT_AUTH',
  BCRYPT_ROUNDS: 10,
  ARGON2_PARAMS: Object.freeze({
    memoryCost: 65536,
    timeCost: 3,
    parallelism: 4,
    hashLength: 32
  })
});


export const PAGINATION_DEFAULTS = Object.freeze({
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
  ORDER: 'desc',
  SORT: 'createdAt'
});

export const REGEX = Object.freeze({
  UUID: /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE: /^\+?[1-9]\d{1,14}$/,
  SLUG: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
  DATE_ISO: /^\d{4}-\d{2}-\d{2}$/
});

